common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name = 'signup'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'), # '/'에 해당되는 path
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),

    # comment_views.py
    # 댓글을 등록할 때는 question_id, 수정이나 삭제할 때는 comment_id 필요
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),

    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

pybo/views/base_views.py
# 기본관리. index, detail

from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count

from ..models import Question

import logging
logger = logging.getLogger('pybo')

def index(request):
    logger.info("INFO 레벨로 출력")
    # pybo에서 목록이 출력되도록
    page = request.GET.get('page','1') #페이지
    kw = request.GET.get('kw','') #검색어
    so = request.GET.get('so','recent') #정렬기준

    # 정렬
    if so == 'recommend':
        question_list = Question.objects.annotate(num_voter=Count('voter')).order_by('-num_voter', '-create_date')
    elif so == 'popular':
        question_list = Question.objects.annotate(num_answer=Count('answer')).order_by('-num_answer','-create_date')
    else: #recent
        question_list = Question.objects.order_by('-create_date')

    # 조회, 검색

    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) | #제목 검색
            Q(content__icontains=kw) | #내용 검색
            Q(author__username__icontains=kw) | #질문 작성자 검색
            Q(answer__author__username__icontains=kw) | #답글 작성자 검색
            Q(answer__content__icontains=kw) #답글 내용 검색
        ).distinct() #중복 제거

    # 페이징 처리
    paginator = Paginator(question_list, 10) #페이지당 10개씩 보여주기
    page_obj = paginator.get_page(page)

    context = {'question_list': page_obj, 'page':page, 'kw':kw, 'so':so}
    return render(request, 'pybo/question_list.html', context)
    # render : 파이썬 데이터를 템플릿에 적용해 HTML로 반환하는 함수

def detail(request, question_id):
    # pybo 내용 출력
    question = get_object_or_404(Question, pk=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)
    # 로컬호스트/pybo/2 페이지가 요청되면 최종적으로 detail 함수의 매개변수인 question_id에는 2라는 값 전달

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- meta tags  -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-sclae=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>PYBO PROJECT</title>
</head>
<body>

<!--네비게이션 바-->
{% include "navbar.html" %}

<!--기본 템플릿 안에 삽입될 내용 시작-->
{% block content %}
{% endblock %}
<!--기본 템플릿 안에 삽입될 내용 끝-->

<!-- jQuery JS -->
<script src="{% static 'jquery-3.6.0.min.js' %}"></script>
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- js 시작 -->
{% block script %}
{% endblock %}
<!-- js 끝 -->

</body>
</html>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %} <!--필드 오류 출력 : 사용자가 입력한 필드 값 오류-->
            <div class="alert alert-danger">
                <strong>{{ filed.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %} <!--넌필드 오류 출력-->
        <div class="alert alert-danger">
            <strong> {{ error }} </strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
<!-- 네비게이션바 -->
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <button class="navbar-toggler ml-auto" type="button" data-toggle="collapse" data-target="#navbarNav"
        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse flex-grow-0" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item ">
                {% if user.is_authenticated %} <!--현재 사용자가 로그인 중인지 판별-->
                <ul class="list-inline">
                    <li class="list-inline-item"><a href=# class="nav-link active"> {{ user.username }} (접속 중) </a></li>
                    <li class="list-inline-item"><a href="{% url 'common:update' %}" class="nav-link"> 회원정보수정 </a></li>
                    <li class="list-inline-item"><a href="{% url 'common:logout' %}" class="nav-link"> 로그아웃 </a></li>
                </ul>
                {% else %}
                <a class="nav-link" href=" {% url 'common:login' %} ">로그인</a>
                {% endif %}
            </li>
        </ul>
    </div>
</nav>